CREATE OR ALTER PROCEDURE GetMovieDetailsOrderByTotalForYearDesc_SP
AS
BEGIN
SELECT MOVIE,GENRE,[YEAR],[MPAA RATING],[TOTAL FOR YEAR] FROM TEMP_STAGE.LANDING_MOVIEDETAILS ORDER BY [TOTAL FOR YEAR] DESC
END;

EXEC GetMovieDetailsOrderByTotalForYearDesc_SP