CREATE OR ALTER PROCEDURE GetTotalTicketSoldsByGenre_SP
AS
BEGIN
SELECT GENRE,SUM(CAST(REPLACE([TICKETS SOLD],',','')  AS INT)) AS TOTAL FROM TEMP_STAGE.LANDING_MOVIEDETAILS GROUP BY GENRE ORDER BY TOTAL DESC
END;

EXEC GetTotalTicketSoldsByGenre_SP